[package]
name = "throbber"
version = "1.0.0"
authors = ["Thomas Lindae <thomas.lindae@in.tum.de>"]
edition = "2024"
description = "Display a throbber animation in the terminal."
license = "MIT"
repository = "https://github.com/Treeniks/throbber"

[dependencies]
